project_id = "rzmgyvkvfjbcsxegafko"

[functions.dispatch-wahl-fix]
verify_jwt = false

[functions.update-wahl-fix]
verify_jwt = false

[functions.record-wahl-activity]
verify_jwt = false

[functions.wahl-chat]
verify_jwt = false
